version: "3.9"
services:
  db:
    image: postgres:13
    restart: always
    container_name: cars-sales
    ports:
      - 5432:5432
    environment:
      - POSTGRES_USER=
      - POSTGRES_PASSWORD=
      - POSTGRES_DB=
